# Generated by Django 4.2.2 on 2023-06-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.Field(max_length=100, primary_key=True, serialize=False),
        ),
    ]
