# Generated by Django 4.2.2 on 2023-06-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productId',
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
