# Generated by Django 4.2.2 on 2023-06-30 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_product_cityid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cityId',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
