# Generated by Django 4.2.2 on 2023-06-30 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_product_cityid_delete_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
