# Generated by Django 4.2.2 on 2023-06-30 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_product_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
