# Generated by Django 4.2.2 on 2023-06-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0014_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(max_length=200)),
                ('discounted_price', models.FloatField()),
                ('quantity', models.FloatField(max_length=200)),
                ('type', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('AJ', 'آجیل'), ('KH', 'خشکبار'), ('ZA', 'زعفران')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
